export const VIZ_SWITCH = "VIZ_SWITCH"
export const UPDATE_QUERY = "UPDATE_QUERY"
export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_PASS = "UPDATE_PASS"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
